armyref/armyref/urls.py
from django.contrib import admin
from django.urls import include, path

from armyref.views import health_check

urlpatterns = [
    path('', include('references.urls')),
    path('health/', health_check, name='health_check'),
    path('admin/', admin.site.urls),
]

armyref/references/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.HomeView.as_view(), name='index'),
]

armyref/armies/models.py
from django.db import models
from ordered_model.models import OrderedModel


class Game(OrderedModel):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class Phase(OrderedModel):
    name = models.CharField(max_length=255)
    game = models.ForeignKey(Game, on_delete=models.CASCADE)

    order_with_respect_to = 'game'

    def __str__(self):
        return '{name} ({game})'.format(name=self.name, game=self.game)


class Warscroll(OrderedModel):
    name = models.CharField(max_length=255)
    game = models.ForeignKey(Game, on_delete=models.CASCADE)

    order_with_respect_to = 'game'

    def __str__(self):
        return self.name


class Rule(OrderedModel):
    name = models.CharField(max_length=255)
    wording = models.TextField(blank=True)
    warscroll = models.ForeignKey(Warscroll, on_delete=models.CASCADE, blank=True)

    def __str__(self):
        return self.name


class WeaponProfile(OrderedModel):
    MELEE = 'MELEE'
    MISSILE = 'MISSILE'
    TYPES = (
        (MELEE, 'Melee'),
        (MISSILE, 'Missile'),
    )

    name = models.CharField(max_length=255)
    weapon_type = models.CharField(max_length=15, choices=TYPES)
    wording = models.TextField(blank=True)
    warscroll = models.ForeignKey(Warscroll, on_delete=models.CASCADE)

    order_with_respect_to = 'warscroll'

    def __str__(self):
        return self.name

armyref/references/models.py
from django.db import models
from ordered_model.models import OrderedModel


class Reference(OrderedModel):
    START_SUB_PHASE = 0
    DURING_SUB_PHASE = 1
    END_SUB_PHASE = 2
    SUB_PHASES = (
        (START_SUB_PHASE, 'Start of phase'),
        (DURING_SUB_PHASE, 'During phase'),
        (END_SUB_PHASE, 'End of phase'),
    )

    name = models.CharField(max_length=255)
    details = models.TextField(blank=True)
    phase = models.ForeignKey('armies.Phase', on_delete=models.CASCADE)
    sub_phase = models.IntegerField(choices=SUB_PHASES, default=DURING_SUB_PHASE)

    order_with_respect_to = ('phase', 'sub_phase')

    class Meta:
        ordering = ['phase', 'sub_phase', 'order']

    def __str__(self):
        return self.name

    @property
    def non_default_sub_phase(self):
        return self.sub_phase != self.DURING_SUB_PHASE

armyref/armies/views.py
from django.shortcuts import render

# Create your views here.

armyref/armyref/views.py
from django.http import JsonResponse

from armies.models import Game


def health_check(self):
    if Game.objects.exists():
        return JsonResponse({'db-access': True}, status=200)
    else:
        return JsonResponse({'db-access': False}, status=503)

armyref/references/views.py
from django.views.generic import TemplateView

from armies.models import Phase
from references.models import Reference


class HomeView(TemplateView):
    template_name = 'references/home.html'
    game = 'Age of Sigmar'

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data()
        context.update(title='Welcome to army references!',
                       references=Reference.objects.filter(phase__game__name=self.game))
        return context

armyref/references/templates/references/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'references/css/main.css' %}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css" integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay" crossorigin="anonymous">
    <!--[if IE]>
      <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <title>{{ title }}</title>
  </head>
 
  <body>
    <div class "container">
      {% block title %}<h1>{{ title }}</h1>{% endblock %}

      {% block content %}{% endblock %}
    </div>

    {% block js %}
      <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
      <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    {% endblock js %}
  </body>
</html>

armyref/references/templates/references/home.html
{% extends 'references/base.html' %}

{% load markdownify %}

{% block content %}
  {% regroup references by phase as phases %}
  {% for phase, references in phases %}
    <h4 data-toggle="collapse" data-target="#phase-{{ phase.id }}" aria-expanded="true" aria-controls="phase-{{ phase.id }}">
      {{ phase.name }} phase <span class="fas text-muted small" aria-hidden="true"></span>
    </h4>
    <div class="collapse show" id="phase-{{ phase.id }}">
      <div class="card-columns">
        {% for ref in references %}
          <div class="reference card {% if ref.sub_phase == 0 %}border-info{% endif %}{% if ref.sub_phase == 2 %}border-danger{% endif %}">
            <h5 class="card-header {% if ref.sub_phase == 0 %}text-info{% endif %}{% if ref.sub_phase == 2 %}text-danger{% endif %}"
                data-toggle="collapse" data-target="#card-body-{{ ref.id }}" aria-expanded="true" aria-controls="card-body-{{ ref.id }}">{{ ref.name }}</h5>
            <div class="collapse show" id="card-body-{{ ref.id }}">
              <div class="card-body">
                {% if ref.details %}
                  <p class="card-text">{{ ref.details|markdownify }}</p>
                {% endif %}
              </div>
            </div>
            {% if ref.non_default_sub_phase %}
            <div class="card-footer text-muted">{{ ref.get_sub_phase_display }}</div>
            {% endif %}
          </div>
        {% endfor %}
      </div>
    </div>
  {% endfor %}
{% endblock %}